version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"

