name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest -f Dockerfile.react .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest -f Dockerfile.node .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Deploy to AWS
        run: |
          aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment